apiVersion: v1
kind: ServiceAccount
metadata:
  name: pagekite-proxy
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pagekite-proxy
subjects:
- kind: ServiceAccount
  name: pagekigte-proxy
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
